#pragma once 
#include <thread>
#include <iostream>
#include <string>
#include <vector>
#include <windows.h>
#include <tlhelp32.h>
#include <comdef.h>
#include <mmdeviceapi.h>
#include <audiopolicy.h>
#include <map>
#include <functiondiscoverykeys_devpkey.h>
#include <dwmapi.h>
#include <format>
#include <array>
#include <wrl/client.h>
#include <set>
#include <functional>
#include <unordered_map>
#include <psapi.h>   
#include <algorithm>
#include <thread>
#include <mutex>
#include <condition_variable>
#include <queue>
#include <atomic>